### PR TITLE
update installation documentation.

### PR DESCRIPTION
**Pull request by milon27**

### CODE REVIEW

**Comment by gargVader** [comment]
Why was this necessary and how was the library running without it previously?

**Comment by milon27** [comment]
not sure but it's required now.

**Comment by ashu9152** [comment]
So I have add maven {jitpack } in both buildle.gradle?

**Comment by milon27** [comment]
@ashu9152 not in both build.gradle only at the project level. both in build script and all projects .

**Comment by Dhina17** [comment]
Oops. I haven't seen this . Take a look https://github.com/ismaeldivita/chip-navigation-bar/pull/74

**Comment by Dhina17** [comment]
Just tried with this patch. Its not working.

**Comment by codersanjeev** [comment]
changing dependency name in build.gradle app file from ```implementation 'com.ismaeldivita.chipnavigation:chip-navigation-bar:1.3.4'``` to ```implementation 'com.github.ismaeldivita:chip-navigation-bar:1.3.4'``` worked for me.

**Comment by ismaeldivita** [comment]
Fixed on https://github.com/ismaeldivita/chip-navigation-bar/pull/74

**Pull request closed without merging**
